In [2]:
import pandas as pd
import numpy as np

In [2]:
elemenatry = pd.read_csv('external_data/國小基本資料.csv')
senior = pd.read_csv('external_data/國中基本資料.csv')
high = pd.read_csv('external_data/高中基本資料.csv')
college = pd.read_csv('external_data/大學基本資料.csv')

elemenatry = elemenatry[['lat','lng']]
senior = senior[['lat','lng']]
high = high[['lat','lng']]
college = college[['lat','lng']]

data_schools = pd.concat([elemenatry, senior, high, college], axis=0, ignore_index = True)

data_schools

            lat         lng
0     25.174899  121.435956
1     24.912039  121.495865
2     24.983012  121.439480
3     25.074187  121.389928
4     25.007022  121.521715
...         ...         ...
4948  25.013258  121.540561
4949  25.013258  121.540561
4950  25.013258  121.540561
4951  23.696060  120.534043
4952  23.696060  120.534043

[4953 rows x 2 columns]

In [24]:
train = pd.read_csv('training_data.csv')
test = pd.read_csv('public_dataset.csv')

data = pd.concat([train,test])
data.reset_index(inplace=True, drop=True)
data

,ID,縣市,鄉鎮市區,路名,土地面積,使用分區,移轉層次,總樓層數,主要用途,主要建材,...,建物面積,車位面積,車位個數,橫坐標,縱坐標,備註,主建物面積,陽台面積,附屬建物面積,單價
0,TR-1,台北市,大安區,敦化南路二段,-0.256716,NaN,11,11,住家用,鋼筋混凝土造,...,-0.174154,-0.819326,0.0,305266,2768378,NaN,0.393926,0.183700,-0.438452,4.627714
1,TR-2,台北市,萬華區,水源路,0.100134,NaN,7,12,住家用,鋼筋混凝土造,...,0.314204,-0.819326,0.0,300677,2767990,NaN,-0.316131,0.608577,-0.438452,1.887258
2,TR-3,高雄市,鳳山區,北忠街,0.181921,NaN,10,15,集合住宅,其他,...,0.423366,0.161624,1.0,184815,2504666,NaN,-0.098871,-0.360620,1.525881,1.489072
3,TR-4,新北市,新莊區,福前街,0.085594,NaN,9,14,集合住宅,鋼筋混凝土造,...,0.164249,0.524653,1.0,296653,2772355,NaN,-0.071147,0.315088,0.231984,2.051217
4,TR-5,新北市,板橋區,文化路一段,-0.938116,NaN,41,43,住家用,鋼骨造,...,0.985839,0.532377,1.0,297377,2768472,NaN,0.791954,1.719400,-0.438452,3.269198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17622,PU-5872,台南市,中西區,中華西路二段,0.560113,NaN,5,5,集合住宅,鋼筋混凝土造,...,-0.788335,-0.016028,1.0,166751,2545157,NaN,-0.867769,-1.078987,-0.438452,NaN
17623,PU-5873,台中市,北區,育樂街,-1.020142,NaN,5,22,集合住宅,鋼筋混凝土造,...,-0.910137,0.799628,1.0,218814,2672567,NaN,-1.107095,-0.754784,-0.438452,NaN
17624,PU-5874,新北市,新店區,安康路二段,-0.662691,NaN,10,12,住家用,鋼筋混凝土造,...,-0.459699,0.004054,1.0,301609,2761359,NaN,-0.474267,-0.131972,-0.438452,NaN
17625,PU-5875,台北市,信義區,忠孝東路五段,0.513752,NaN,2,5,住家用,鋼筋混凝土造,...,0.357294,-0.819326,0.0,308833,2770624,NaN,0.926327,1.243333,-0.316749,NaN
17626,PU-5876,新北市,中和區,中正路,-1.043623,NaN,22,22,住家用,鋼筋混凝土造,...,-0.617697,1.663173,2.0,298924,2765519,NaN,-0.742448,-0.258240,-0.438452,NaN

In [ ]:
data['school_numbs_within_1km'] = 0

# 遍历 data 数据集
for index, row_data in data.iterrows():
        lat1, lng1 = row_data['lat'], row_data['lng']
        school_count = 0
    # 遍历 contrast 数据集
        for _, row_contrast in data_schools.iterrows():
            lat2, lng2 = row_contrast['lat'], row_contrast['lng']
        
        # 计算两点之间的距离
            distance = geodesic((lat1, lng1), (lat2, lng2)).kilometers
        
        # 如果距离小于等于1公里，则将 within_1km 列设置为 True
            if distance <= 1:
                school_count += 1
        
        data.at[index, 'school_numbs_within_1km'] = school_count
    
data['school_numbs_within_1km'].value_counts()

In [5]:
import math

def twd97_to_lonlat(x=174458.0,y=2525824.0):
    """
    Parameters
    ----------
    x : float
        TWD97 coord system. The default is 174458.0.
    y : float
        TWD97 coord system. The default is 2525824.0.
    Returns
    -------
    list
        [longitude, latitude]
    """
    
    a = 6378137
    b = 6356752.314245
    long_0 = 121 * math.pi / 180.0
    k0 = 0.9999
    dx = 250000
    dy = 0
    
    e = math.pow((1-math.pow(b, 2)/math.pow(a,2)), 0.5)
    
    x -= dx
    y -= dy
    
    M = y / k0
    
    mu = M / ( a*(1-math.pow(e, 2)/4 - 3*math.pow(e,4)/64 - 5 * math.pow(e, 6)/256))
    e1 = (1.0 - pow((1   - pow(e, 2)), 0.5)) / (1.0 +math.pow((1.0 -math.pow(e,2)), 0.5))
    
    j1 = 3*e1/2-27*math.pow(e1,3)/32
    j2 = 21 * math.pow(e1,2)/16 - 55 * math.pow(e1, 4)/32
    j3 = 151 * math.pow(e1, 3)/96
    j4 = 1097 * math.pow(e1, 4)/512
    
    fp = mu + j1 * math.sin(2*mu) + j2 * math.sin(4* mu) + j3 * math.sin(6*mu) + j4 * math.sin(8* mu)
    
    e2 = math.pow((e*a/b),2)
    c1 = math.pow(e2*math.cos(fp),2)
    t1 = math.pow(math.tan(fp),2)
    r1 = a * (1-math.pow(e,2)) / math.pow( (1-math.pow(e,2)* math.pow(math.sin(fp),2)), (3/2))
    n1 = a / math.pow((1-math.pow(e,2)*math.pow(math.sin(fp),2)),0.5)
    d = x / (n1*k0)
    
    q1 = n1* math.tan(fp) / r1
    q2 = math.pow(d,2)/2
    q3 = ( 5 + 3 * t1 + 10 * c1 - 4 * math.pow(c1,2) - 9 * e2 ) * math.pow(d,4)/24
    q4 = (61 + 90 * t1 + 298 * c1 + 45 * math.pow(t1,2) - 3 * math.pow(c1,2) - 252 * e2) * math.pow(d,6)/720
    lat = fp - q1 * (q2 - q3 + q4)
    
    
    q5 = d
    q6 = (1+2*t1+c1) * math.pow(d,3) / 6
    q7 = (5 - 2 * c1 + 28 * t1 - 3 * math.pow(c1,2) + 8 * e2 + 24 * math.pow(t1,2)) * math.pow(d,5) / 120
    lon = long_0 + (q5 - q6 + q7) / math.cos(fp)
    
    lat = (lat*180) / math.pi
    lon = (lon*180) / math.pi
    return [lon, lat]

twd97_to_lonlat(x = 305266, y = 2768378)

[121.54760767694441, 25.022469126806683]

In [6]:
df_ll = pd.DataFrame(zip(data['橫坐標'],data['縱坐標']))
print(df_ll)

            0        1
0      305266  2768378
1      300677  2767990
2      184815  2504666
3      296653  2772355
4      297377  2768472
...       ...      ...
17622  166751  2545157
17623  218814  2672567
17624  301609  2761359
17625  308833  2770624
17626  298924  2765519

[17627 rows x 2 columns]

In [7]:
result = df_ll.apply(lambda row: pd.Series(twd97_to_lonlat(row[0], row[1])), axis=1)
result = result.rename(columns={0: 'lng', 1: 'lat'})
result

              lng        lat
0      121.547608  25.022469
1      121.502124  25.019127
2      120.365799  22.640966
3      121.462402  25.058663
4      121.469444  25.023585
...           ...        ...
17622  120.187896  23.005809
17623  120.693103  24.158104
17624  121.511111  24.959230
17625  121.583046  25.042611
17626  121.484668  24.996876

[17627 rows x 2 columns]

In [8]:
data = pd.concat([data,result],axis=1)
data.head()

,ID,縣市,鄉鎮市區,路名,土地面積,使用分區,移轉層次,總樓層數,主要用途,主要建材,...,車位個數,橫坐標,縱坐標,備註,主建物面積,陽台面積,附屬建物面積,單價,lng,lat
0,TR-1,台北市,大安區,敦化南路二段,-0.256716,NaN,11,11,住家用,鋼筋混凝土造,...,0.0,305266,2768378,NaN,0.393926,0.183700,-0.438452,4.627714,121.547608,25.022469
1,TR-2,台北市,萬華區,水源路,0.100134,NaN,7,12,住家用,鋼筋混凝土造,...,0.0,300677,2767990,NaN,-0.316131,0.608577,-0.438452,1.887258,121.502124,25.019127
2,TR-3,高雄市,鳳山區,北忠街,0.181921,NaN,10,15,集合住宅,其他,...,1.0,184815,2504666,NaN,-0.098871,-0.360620,1.525881,1.489072,120.365799,22.640966
3,TR-4,新北市,新莊區,福前街,0.085594,NaN,9,14,集合住宅,鋼筋混凝土造,...,1.0,296653,2772355,NaN,-0.071147,0.315088,0.231984,2.051217,121.462402,25.058663
4,TR-5,新北市,板橋區,文化路一段,-0.938116,NaN,41,43,住家用,鋼骨造,...,1.0,297377,2768472,NaN,0.791954,1.719400,-0.438452,3.269198,121.469444,25.023585

In [9]:
from geopy.distance import geodesic

data['school_numbs_within_1km'] = 0

# 提取经度和纬度为NumPy数组
data_coords = data[['lat', 'lng']].to_numpy()
school_coords = data_schools[['lat', 'lng']].to_numpy()

# 对每个点计算与学校的距离
distances = geodesic(data_coords[:, np.newaxis, :], school_coords).kilometers

# 找到距离小于等于1公里的学校数量
schools_within_1km = np.sum(distances <= 1, axis=1)

# 更新数据集中的计数列
data['school_numbs_within_1km'] = schools_within_1km

school_counts = data['school_numbs_within_1km'].value_counts()

ValueError: When creating a Point from sequence, it must not have more than 3 items.

In [10]:
import numpy as np
from geopy.distance import geodesic

data['school_numbs_within_1km'] = 0

# 提取经度和纬度为NumPy数组
data_coords = data[['lng', 'lat']].to_numpy()
school_coords = data_schools[['lng', 'lat']].to_numpy()

# 对每个点计算与学校的距离
distances = geodesic(data_coords[:, np.newaxis, :], school_coords).kilometers

# 找到距离小于等于1公里的学校数量
schools_within_1km = np.sum(distances <= 1, axis=1)

# 更新数据集中的计数列
data['school_numbs_within_1km'] = schools_within_1km

school_counts = data['school_numbs_within_1km'].value_counts()

ValueError: When creating a Point from sequence, it must not have more than 3 items.

In [11]:
from scipy.spatial.distance import cdist
from geopy.distance import geodesic

data['school_numbs_within_1km'] = 0

# 提取经度和纬度为NumPy数组
data_coords = data[['lng', 'lat']].to_numpy()
school_coords = data_schools[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(data_coords, school_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances / 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
schools_within_1km = np.sum(distances_in_km <= 1, axis=1)

# 更新数据集中的计数列
data['school_numbs_within_1km'] = schools_within_1km

school_counts = data['school_numbs_within_1km'].value_counts()

In [13]:
data['school_numbs_within_1km']

0        4948
1        4948
2        4948
3        4948
4        4948
         ...
17622    4948
17623    4948
17624    4948
17625    4948
17626    4948
Name: school_numbs_within_1km, Length: 17627, dtype: int64

In [22]:
data_bus = pd.read_csv('external_data/公車站點資料.csv')
data_bus.columns

Index(['縣市', '站點UID', '業管機關代碼', '站點名稱', 'lat', 'lng'], dtype='object')

In [46]:
from scipy.spatial.distance import cdist

# 將經緯度轉成 Numpy，用於矩陣運算。
data_coords = data[['lng', 'lat']].to_numpy()
bus_coords = data_bus[['lng', 'lat']].to_numpy()

# 計算歐式距離矩陣
distances = cdist(data_coords, bus_coords, metric='euclidean')

# 將經緯度距離轉換為公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 統計距離目標小於200公尺的公車站總數
bus_within = np.sum(distances_in_km <= 0.2, axis=1)

# 將結果作為新增特徵
data['bus_numbs_within_0.2km'] = bus_within

bus_counts = data['bus_numbs_within_0.2km'].value_counts()
bus_counts

bus_numbs_within_0.2km
0      2730
2      1145
4       948
6       804
8       635
       ...
135       1
114       1
115       1
109       1
134       1
Name: count, Length: 119, dtype: int64

In [47]:
data[data['bus_numbs_within_0.2km']>100]

,ID,縣市,鄉鎮市區,路名,土地面積,使用分區,移轉層次,總樓層數,主要用途,主要建材,...,備註,主建物面積,陽台面積,附屬建物面積,單價,lng,lat,school_numbs_within_1km,bus_numbs_within_1km,bus_numbs_within_0.2km
342,TR-343,新北市,新莊區,新泰路,-0.193171,NaN,3,15,住家用,鋼筋混凝土造,...,NaN,1.966519,2.151103,15.137429,1.208000,121.448855,25.034771,11,177,101
1005,TR-1006,新北市,新莊區,立信三街,-0.684586,NaN,13,13,住家用,鋼筋混凝土造,...,NaN,-0.624200,0.159811,0.114551,2.074640,121.444164,25.050197,7,149,101
1870,TR-1871,新北市,淡水區,中正路,-0.629693,NaN,3,8,其他,鋼筋混凝土造,...,NaN,-0.273132,-0.696768,-0.438452,1.137732,121.443506,25.169839,8,349,172
1991,TR-1992,台北市,萬華區,成都路,-1.106206,NaN,6,12,商業用,鋼筋混凝土造,...,NaN,1.612056,-1.009027,-0.438452,2.660207,121.507431,25.042112,8,420,130
2191,TR-2192,台北市,萬華區,漢中街,-0.787978,NaN,4,11,商業用,鋼筋混凝土造,...,NaN,0.183738,1.062462,-0.438452,2.449403,121.507002,25.041446,8,334,135
2361,TR-2362,新北市,淡水區,中山北路一段,-0.904661,NaN,12,14,住家用,鋼筋混凝土造,...,NaN,-0.893795,-0.667761,-0.197181,1.208000,121.445951,25.179455,17,374,106
2877,TR-2878,台北市,萬華區,漢中街,-1.141776,NaN,3,15,住家用,鋼筋混凝土造,...,NaN,-0.693508,-0.584150,-0.438452,3.690806,121.506704,25.041266,8,358,110
3841,TR-3842,台北市,文山區,保儀路,-0.857964,NaN,9,12,住家用,鋼筋混凝土造,...,NaN,-0.556306,0.036955,0.441228,2.660207,121.569941,24.988015,13,338,104
4045,TR-4046,新北市,新店區,北新路一段,0.384740,NaN,4,5,住家用,鋼筋混凝土造,...,NaN,-0.062944,0.060844,-0.438452,2.191753,121.540765,24.966700,5,191,114
4861,TR-4862,新北市,蘆洲區,永安北路二段,-0.329850,NaN,4,9,住家用,鋼筋混凝土造,...,NaN,-0.708219,-0.155860,-0.438452,2.191753,121.480793,25.080471,7,286,117
5130,TR-5131,台北市,北投區,石牌路二段,-0.070480,NaN,3,4,住家用,鋼筋混凝土造,...,NaN,0.014852,-1.227438,-0.438452,2.824166,121.516365,25.116581,17,198,106
5614,TR-5615,新北市,淡水區,中正路,-0.629693,NaN,7,8,住家用,鋼筋混凝土造,...,NaN,-0.273132,-0.696768,-0.438452,1.231422,121.443476,25.169803,8,349,172
5941,TR-5942,新北市,淡水區,中山路,-0.463909,NaN,5,6,住家用,鋼筋混凝土造,...,NaN,-0.552345,-0.265066,-0.438452,1.301691,121.443093,25.170950,12,298,117
6000,TR-6001,台北市,士林區,志成街,2.583090,NaN,6,6,住家用,鋼筋混凝土造,...,NaN,0.871164,-0.157567,-0.438452,3.503425,121.529874,25.096816,14,317,128
6274,TR-6275,台北市,中山區,北安路,0.985170,住,2,4,住家用,鋼筋混凝土造,...,NaN,-0.250500,0.120566,-0.438452,3.690806,121.556915,25.084683,11,192,102
6695,TR-6696,新北市,淡水區,中正路,-0.629693,NaN,8,8,住家用,鋼筋混凝土造,...,NaN,-0.236639,-0.696768,-0.438452,1.254845,121.443842,25.169495,7,340,172
7110,TR-7111,台北市,文山區,萬壽路,1.384488,住,10,10,住家用,鋼筋混凝土造,...,NaN,0.600154,0.098383,1.703098,2.917857,121.575628,24.988418,14,210,125
9012,TR-9013,新北市,淡水區,水源街一段,-0.194565,NaN,3,5,住家用,鋼筋混凝土造,...,NaN,-0.573279,0.325326,-0.438452,1.067464,121.442353,25.172144,25,341,130
9093,TR-9094,新北市,淡水區,北新路,-0.329249,住,2,7,住家用,鋼筋混凝土造,...,NaN,-0.025602,0.608577,-0.438452,1.254845,121.445350,25.177859,19,397,104
9151,TR-9152,新北市,板橋區,縣民大道二段,0.071871,NaN,22,32,住家用,鋼骨造,...,NaN,2.946454,0.982264,-0.438452,3.550270,121.463279,25.012401,12,247,105
9905,TR-9906,新北市,五股區,成泰路二段,-1.148169,NaN,9,12,住家用,鋼筋混凝土造,...,NaN,-0.444564,0.356040,-0.438452,1.442227,121.437655,25.084153,2,203,102
10386,TR-10387,新北市,五股區,中興路四段,-0.737243,NaN,12,12,住家用,鋼筋混凝土造,...,NaN,0.422215,-0.106377,-0.438452,1.489072,121.438070,25.083799,2,217,107
10689,TR-10690,台北市,士林區,志成街,2.583090,NaN,5,6,住家用,鋼筋混凝土造,...,NaN,1.265514,0.292905,-0.438452,3.503425,121.530101,25.096563,8,291,128
10711,TR-10712,新北市,新店區,安德街,-0.655553,NaN,4,11,住家用,鋼筋混凝土造,...,NaN,-0.715291,-0.160979,-0.173694,1.582763,121.511080,24.961388,10,196,102
10957,TR-10958,新北市,新莊區,中正路,-0.705591,NaN,12,12,住家用,鋼筋混凝土造,...,NaN,0.384591,-0.065425,-0.438452,1.816990,121.448431,25.035161,12,185,108
11059,TR-11060,新北市,新莊區,立信三街,-0.121575,NaN,12,13,住家用,鋼筋混凝土造,...,NaN,0.038897,3.514464,0.114551,2.004372,121.444324,25.050404,7,161,101
11549,TR-11550,台北市,內湖區,內湖路一段,0.325785,住,4,4,住家用,鋼筋混凝土造,...,NaN,0.157429,1.023216,-0.438452,2.613362,121.564818,25.082938,13,337,133
11647,TR-11648,新北市,三重區,中正南路,-1.108802,NaN,11,13,住家用,鋼筋混凝土造,...,NaN,-1.386309,-0.167805,-0.130991,2.917857,121.493423,25.060748,10,193,104
12000,PU-250,台北市,中正區,延平南路,-1.206354,NaN,6,10,住家用,鋼筋混凝土造,...,NaN,-1.074846,-1.340056,-0.438452,NaN,121.510116,25.044396,8,377,104
12136,PU-386,新北市,淡水區,中正路,-0.629693,NaN,2,8,其他,鋼筋混凝土造,...,NaN,-0.273132,-0.696768,-0.438452,NaN,121.443187,25.169659,11,360,173
12958,PU-1208,台北市,內湖區,瑞光路,0.657857,NaN,3,8,住家用,鋼筋混凝土造,...,NaN,-0.273698,-0.248002,-0.128856,NaN,121.583631,25.069919,4,243,108
12989,PU-1239,台北市,文山區,木柵路三段,-0.599555,NaN,24,24,住家用,鋼骨造,...,NaN,0.427307,1.453212,-0.438452,NaN,121.569901,24.990083,13,320,110
13058,PU-1308,台北市,內湖區,內湖路一段,1.277731,NaN,3,4,工業用,鋼筋混凝土造,...,NaN,0.450221,0.562506,-0.438452,NaN,121.563239,25.084442,12,198,105
13478,PU-1728,台北市,士林區,中正路,0.191510,NaN,5,7,住家用,鋼筋混凝土造,...,NaN,0.593647,0.659767,-0.438452,NaN,121.528484,25.096207,12,333,107
13797,PU-2047,新北市,五股區,中興路四段,-1.211810,NaN,7,11,住家用,鋼筋混凝土造,...,NaN,-0.734245,-0.602920,-0.438452,NaN,121.438465,25.083320,2,213,104
14779,PU-3029,新北市,淡水區,水碓,-0.093216,NaN,4,5,住家用,鋼筋混凝土造,...,NaN,-0.544425,-0.894703,0.022739,NaN,121.444782,25.177012,20,345,115
14909,PU-3159,台北市,萬華區,成都路,-1.106206,NaN,7,12,商業用,鋼筋混凝土造,...,NaN,1.612056,-1.009027,-0.438452,NaN,121.507767,25.042048,13,412,130
15162,PU-3412,新北市,泰山區,仁德路,0.189395,NaN,10,10,住家用,鋼筋混凝土造,...,NaN,0.255875,0.318500,-0.165153,NaN,121.434794,25.057284,5,261,105
16133,PU-4383,台北市,士林區,中正路,-0.383133,NaN,8,16,住家用,鋼筋混凝土造,...,NaN,0.617976,1.502696,-0.438452,NaN,121.518886,25.091330,16,225,109
16416,PU-4666,新北市,淡水區,中山北路一段,-1.155091,NaN,11,23,住家用,鋼筋混凝土造,...,NaN,-0.525471,0.671711,-0.039180,NaN,121.444702,25.179639,18,366,107
16668,PU-4918,台北市,萬華區,漢中街,-0.890866,NaN,13,15,住家用,鋼筋混凝土造,...,NaN,-0.260119,1.557299,-0.438452,NaN,121.507022,25.041599,8,366,134
16718,PU-4968,新北市,板橋區,文化路一段,0.648436,NaN,13,14,住家用,鋼筋混凝土造,...,NaN,0.245974,0.195644,-0.438452,NaN,121.467646,25.022426,11,188,105

In [49]:
csv_file = "bus_numbs_within_0.2km_pu.csv"

pd.Series(data['bus_numbs_within_0.2km']).to_csv(csv_file, index=False)

In [51]:
pr = pd.read_csv('dataset_private_latlng.csv')
pr

,ID,縣市,鄉鎮市區,路名,土地面積,使用分區,移轉層次,總樓層數,主要用途,主要建材,...,車位面積,車位個數,橫坐標,縱坐標,備註,主建物面積,陽台面積,附屬建物面積,lng,lat
0,PR-1,高雄市,前鎮區,鎮海路,-0.541033,NaN,12,14,住家用,鋼筋混凝土造,...,-0.819326,0.0,179750,2499123,NaN,0.127159,0.035249,-0.438452,120.316770,22.590707
1,PR-2,台北市,北投區,大同街,0.753799,NaN,4,7,其他,鋼筋混凝土造,...,0.311470,1.0,300436,2781335,NaN,-0.464083,-0.160979,-0.438452,121.500226,25.139613
2,PR-3,台北市,大同區,大龍街,0.482869,住,6,7,住家用,鋼筋混凝土造,...,-0.819326,0.0,302091,2773374,NaN,0.832407,2.461656,-0.438452,121.516338,25.067685
3,PR-4,新北市,蘆洲區,民族路,0.390940,NaN,4,4,住家用,加強磚造,...,-0.819326,0.0,298394,2775413,NaN,0.052476,-1.642077,-0.438452,121.479765,25.086216
4,PR-5,新北市,新莊區,龍安路,-0.711599,NaN,3,8,住家用,鋼筋混凝土造,...,-0.819326,0.0,292572,2767887,NaN,-0.968196,-0.333319,-0.022099,121.421816,25.018446
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,PR-5871,高雄市,鳳山區,和德街,-0.163249,NaN,25,25,集合住宅,鋼筋混凝土造,...,1.661628,2.0,184250,2502080,NaN,-0.496050,0.946431,0.870392,120.360410,22.617591
5871,PR-5872,台北市,南港區,玉成街,1.118749,NaN,6,17,一般事務所,其他,...,4.845468,3.0,308685,2771134,NaN,2.717029,1.105120,-0.130991,121.581601,25.047221
5872,PR-5873,新北市,林口區,文化二路一段,-0.053200,NaN,14,14,住家用,鋼筋混凝土造,...,-0.819326,0.0,287075,2773585,NaN,0.242296,-0.084194,-0.438452,121.367504,25.070033
5873,PR-5874,高雄市,鳳山區,文龍東路,-0.089851,NaN,2,15,集合住宅,鋼筋混凝土造,...,-0.819326,0.0,185561,2504746,NaN,-0.257007,2.461656,-0.438452,120.373053,22.641717
5874,PR-5875,新竹縣,竹北市,十興路一段,1.475407,NaN,10,14,住家用,鋼筋混凝土造,...,1.748137,2.0,253067,2746655,NaN,1.500031,0.192232,0.501012,121.030342,24.827349

In [35]:
df_pr = pd.DataFrame(zip(pr['橫坐標'],pr['縱坐標']))
print(df_pr)

           0        1
0     179750  2499123
1     300436  2781335
2     302091  2773374
3     298394  2775413
4     292572  2767887
...      ...      ...
5870  184250  2502080
5871  308685  2771134
5872  287075  2773585
5873  185561  2504746
5874  253067  2746655

[5875 rows x 2 columns]

In [36]:
result_pr = df_pr.apply(lambda row: pd.Series(twd97_to_lonlat(row[0], row[1])), axis=1)
result_pr = result_pr.rename(columns={0: 'lng', 1: 'lat'})
result_pr

             lng        lat
0     120.316770  22.590707
1     121.500226  25.139613
2     121.516338  25.067685
3     121.479765  25.086216
4     121.421816  25.018446
...          ...        ...
5870  120.360410  22.617591
5871  121.581601  25.047221
5872  121.367504  25.070033
5873  120.373053  22.641717
5874  121.030342  24.827349

[5875 rows x 2 columns]

In [37]:
pr = pd.concat([pr,result_pr],axis=1)
pr.head()

,ID,縣市,鄉鎮市區,路名,土地面積,使用分區,移轉層次,總樓層數,主要用途,主要建材,...,車位面積,車位個數,橫坐標,縱坐標,備註,主建物面積,陽台面積,附屬建物面積,lng,lat
0,PR-1,高雄市,前鎮區,鎮海路,-0.541033,NaN,12,14,住家用,鋼筋混凝土造,...,-0.819326,0.0,179750,2499123,NaN,0.127159,0.035249,-0.438452,120.316770,22.590707
1,PR-2,台北市,北投區,大同街,0.753799,NaN,4,7,其他,鋼筋混凝土造,...,0.311470,1.0,300436,2781335,NaN,-0.464083,-0.160979,-0.438452,121.500226,25.139613
2,PR-3,台北市,大同區,大龍街,0.482869,住,6,7,住家用,鋼筋混凝土造,...,-0.819326,0.0,302091,2773374,NaN,0.832407,2.461656,-0.438452,121.516338,25.067685
3,PR-4,新北市,蘆洲區,民族路,0.390940,NaN,4,4,住家用,加強磚造,...,-0.819326,0.0,298394,2775413,NaN,0.052476,-1.642077,-0.438452,121.479765,25.086216
4,PR-5,新北市,新莊區,龍安路,-0.711599,NaN,3,8,住家用,鋼筋混凝土造,...,-0.819326,0.0,292572,2767887,NaN,-0.968196,-0.333319,-0.022099,121.421816,25.018446

In [39]:
data.to_csv('dataset_public_latlng.csv', index=False)

In [38]:
pr.to_csv('dataset_private_latlng.csv', index=False)

In [56]:
from scipy.spatial.distance import cdist

# 提取经度和纬度为NumPy数组
pr_coords = pr[['lng', 'lat']].to_numpy()
bus_coords = data_bus[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(pr_coords, bus_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
bus_within = np.sum(distances_in_km <= 0.5, axis=1)

# 更新数据集中的计数列
pr['bus_numbs_within_0.5km'] = bus_within

bus_counts = pr['bus_numbs_within_0.5km'].value_counts()
bus_counts

bus_numbs_within_0.5km
0      177
14      72
28      59
36      58
29      57
      ...
247      1
383      1
324      1
394      1
307      1
Name: count, Length: 320, dtype: int64

In [58]:
csv_file = "bus_numbs_within_0.5km_pr.csv"

pd.Series(pr['bus_numbs_within_0.5km']).to_csv(csv_file, index=False)

In [59]:
atm = pd.read_csv('external_data/ATM資料.csv')
atm.columns

Index(['裝設金融機構代號', '裝設金融機構名稱', '裝設地點', '裝設縣市', '裝設地址', 'lat', 'lng'], dtype='object')

In [60]:
# 提取经度和纬度为NumPy数组
data_coords = data[['lng', 'lat']].to_numpy()
atm_coords = atm[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(data_coords, atm_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
atm_within = np.sum(distances_in_km <= 0.5, axis=1)

# 更新数据集中的计数列
data['atm_numbs_within_0.5km'] = atm_within

atm_counts = data['atm_numbs_within_0.5km'].value_counts()
atm_counts

atm_numbs_within_0.5km
11    801
10    729
8     729
13    698
7     696
     ...
88      1
92      1
97      1
93      1
83      1
Name: count, Length: 93, dtype: int64

In [61]:
csv_file = "atm_numbs_within_0.5km_pu.csv"

pd.Series(data['atm_numbs_within_0.5km']).to_csv(csv_file, index=False)

In [62]:
from scipy.spatial.distance import cdist

# 提取经度和纬度为NumPy数组
pr_coords = pr[['lng', 'lat']].to_numpy()
atm_coords = atm[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(pr_coords, atm_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
atm_within = np.sum(distances_in_km <= 0.5, axis=1)

# 更新数据集中的计数列
pr['atm_numbs_within_0.5km'] = atm_within

atm_counts = pr['atm_numbs_within_0.5km'].value_counts()
atm_counts

atm_numbs_within_0.5km
13     266
11     256
10     256
6      247
12     243
      ...
85       1
95       1
79       1
101      1
81       1
Name: count, Length: 90, dtype: int64

In [63]:
csv_file = "atm_numbs_within_0.5km_pr.csv"

pd.Series(pr['atm_numbs_within_0.5km']).to_csv(csv_file, index=False)

In [69]:
bike = pd.read_csv('external_data/腳踏車站點資料.csv')
bike.columns

Index(['縣市', '站點UID', '站點ID', '站點名稱', '站點地址', '腳踏車可租借數量', 'lat', 'lng'], dtype='object')

In [70]:
# 提取经度和纬度为NumPy数组
data_coords = data[['lng', 'lat']].to_numpy()
bike_coords = bike[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(data_coords, bike_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
bike_within = np.sum(distances_in_km <= 0.5, axis=1)

# 更新数据集中的计数列
data['bike_numbs_within_0.5km'] = bike_within

bike_counts = data['bike_numbs_within_0.5km'].value_counts()
bike_counts

bike_numbs_within_0.5km
0     2047
7     1492
6     1469
4     1368
8     1309
9     1262
5     1212
10    1182
3     1155
2     1049
11     969
1      773
12     763
13     541
14     371
15     245
16     135
17      87
18      60
19      45
20      34
21      18
23       6
22       6
32       4
25       4
27       4
24       3
29       3
31       3
28       2
30       2
26       2
34       2
Name: count, dtype: int64

In [71]:
csv_file = "bike_numbs_within_0.5km_pu.csv"

pd.Series(data['bike_numbs_within_0.5km']).to_csv(csv_file, index=False)

In [72]:
# 提取经度和纬度为NumPy数组
pr_coords = pr[['lng', 'lat']].to_numpy()
bike_coords = bike[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(pr_coords, bike_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
bike_within = np.sum(distances_in_km <= 0.5, axis=1)

# 更新数据集中的计数列
pr['bike_numbs_within_0.5km'] = bike_within

bike_counts = pr['bike_numbs_within_0.5km'].value_counts()
bike_counts

bike_numbs_within_0.5km
0     647
7     520
6     483
4     453
5     448
8     431
9     419
3     370
2     349
10    348
11    329
12    276
1     269
13    194
14    100
15     91
16     43
17     26
18     22
19     19
20      9
21      8
22      6
23      3
30      2
28      2
26      2
27      1
24      1
32      1
31      1
29      1
25      1
Name: count, dtype: int64

In [73]:
csv_file = "bike_numbs_within_0.5km_pr.csv"

pd.Series(pr['bike_numbs_within_0.5km']).to_csv(csv_file, index=False)

In [74]:
hos = pd.read_csv('external_data/醫療機構基本資料.csv')
hos.columns

Index(['機構代碼', '機構名稱', '權屬別', '型態別', '縣市鄉鎮', '電話', '地址', '診療科別', '醫師', '中醫師',
       '牙醫師', '藥師', '藥劑生', '護理師', '護士', '助產士', '助產師', '醫事檢驗師', '醫事檢驗生', '鑲牙生',
       '中藥員', '齒模員', '接骨員', '物理治療師', '職能治療師', '醫事放射師', '醫事放射士', '物理治療生',
       '職能治療生', '呼吸治療師', '諮商心理師', '臨床心理師', '營養師', '語言治療師', '牙體技術師', '聽力師',
       '牙體技術生', '驗光師', '驗光生', 'lat', 'lng'],
      dtype='object')

In [75]:
# 提取经度和纬度为NumPy数组
data_coords = data[['lng', 'lat']].to_numpy()
hos_coords = hos[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(data_coords, hos_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
hos_within = np.sum(distances_in_km <= 0.5, axis=1)

# 更新数据集中的计数列
data['hos_numbs_within_0.5km'] = hos_within

hos_counts = data['hos_numbs_within_0.5km'].value_counts()
hos_counts

hos_numbs_within_0.5km
0      1082
1       776
2       624
3       591
5       556
       ...
159       1
115       1
140       1
176       1
107       1
Name: count, Length: 179, dtype: int64

In [76]:
csv_file = "hos_numbs_within_0.5km_pu.csv"

pd.Series(data['hos_numbs_within_0.5km']).to_csv(csv_file, index=False)

In [77]:
# 提取经度和纬度为NumPy数组
pr_coords = pr[['lng', 'lat']].to_numpy()
hos_coords = hos[['lng', 'lat']].to_numpy()

# 计算距离矩阵
distances = cdist(pr_coords, hos_coords, metric='euclidean')

# 转换为公里
distances_in_km = distances * 111.32  # 1度约等于111.32公里

# 统计距离小于等于1公里的学校数量
hos_within = np.sum(distances_in_km <= 0.5, axis=1)

# 更新数据集中的计数列
pr['hos_numbs_within_0.5km'] = hos_within

hos_counts = pr['hos_numbs_within_0.5km'].value_counts()
hos_counts

hos_numbs_within_0.5km
0      358
2      240
1      237
5      189
3      186
      ...
152      1
118      1
113      1
206      1
99       1
Name: count, Length: 143, dtype: int64

In [8]:
import pandas as pd
print(pd.Series({'lat':[120], 'lng':[26]}).to_numpy())

[list([120]) list([26])]

In [78]:
csv_file = "hos_numbs_within_0.5km_pr.csv"

pd.Series(pr['hos_numbs_within_0.5km']).to_csv(csv_file, index=False)

In [4]:
private = pd.read_csv('data_pr_1108.csv')
private

,土地面積,移轉層次,總樓層數,屋齡,車位面積,橫坐標,縱坐標,主建物面積,附屬建物面積,平均單價元平方公尺,...,主要用途_集合住宅,主要建材_其他,主要建材_加強磚造,主要建材_鋼筋混凝土造,主要建材_鋼骨造,hospital_within_1km,mrt_numbs_within_1km,school_numbs_within_1km,縣市區域價格,store_numbs_within_0.5km
0,-0.541033,12,14,27.916667,-0.819326,179750,2499123,0.127159,-0.438452,103816.813612,...,0,0,0,1,0,1,4,10,4,6
1,0.753799,4,7,0.750000,0.311470,300436,2781335,-0.464083,-0.438452,103816.813612,...,0,0,0,1,0,1,2,17,10,12
2,0.482869,6,7,43.916667,-0.819326,302091,2773374,0.832407,-0.438452,82963.562500,...,0,0,0,1,0,0,4,32,10,18
3,0.390940,4,4,45.416667,-0.819326,298394,2775413,0.052476,-0.438452,137138.842105,...,0,0,1,0,0,1,2,6,9,24
4,-0.711599,3,8,27.250000,-0.819326,292572,2767887,-0.968196,-0.022099,201314.470149,...,0,0,0,1,0,0,0,12,9,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,-0.163249,25,25,1.500000,1.661628,184250,2502080,-0.496050,0.870392,55194.812500,...,1,0,0,1,0,1,1,6,4,3
5871,1.118749,6,17,17.583333,4.845468,308685,2771134,2.717029,-0.130991,133163.601485,...,0,1,0,0,0,0,3,8,10,21
5872,-0.053200,14,14,27.083333,-0.819326,287075,2773585,0.242296,-0.438452,103816.813612,...,0,0,0,1,0,0,1,4,9,14
5873,-0.089851,2,15,4.166667,-0.819326,185561,2504746,-0.257007,-0.438452,82639.428571,...,1,0,0,1,0,0,0,1,4,4
5874,1.475407,10,14,7.916667,1.748137,253067,2746655,1.500031,0.501012,69580.457831,...,0,0,0,1,0,0,0,4,8,10

In [5]:
private.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5875 entries, 0 to 5874
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   土地面積                      5875 non-null   float64
 1   移轉層次                      5875 non-null   int64
 2   總樓層數                      5875 non-null   int64
 3   屋齡                        5875 non-null   float64
 4   車位面積                      5875 non-null   float64
 5   橫坐標                       5875 non-null   int64
 6   縱坐標                       5875 non-null   int64
 7   主建物面積                     5875 non-null   float64
 8   附屬建物面積                    5875 non-null   float64
 9   平均單價元平方公尺                 5875 non-null   float64
 10  主要用途_商業用                  5875 non-null   int64
 11  主要用途_集合住宅                 5875 non-null   int64
 12  主要建材_其他                   5875 non-null   int64
 13  主要建材_加強磚造                 5875 non-null   int64
 14  主要建材_鋼筋混凝土造               5875 non-null   int64
 15  主要建材_鋼骨造                  5875 non-null   int64
 16  hospital_within_1km       5875 non-null   int64
 17  mrt_numbs_within_1km      5875 non-null   int64
 18  school_numbs_within_1km   5875 non-null   int64
 19  縣市區域價格                    5875 non-null   int64
 20  store_numbs_within_0.5km  5875 non-null   int64
dtypes: float64(6), int64(15)
memory usage: 964.0 KB

In [7]:
new_column_data = private['store_numbs_within_0.5km']
private.drop('store_numbs_within_0.5km', axis=1, inplace=True)
# 在index 15的位置插入新列
private.insert(19, 'store_numbs_within_0.5km', new_column_data)

In [8]:
private

,土地面積,移轉層次,總樓層數,屋齡,車位面積,橫坐標,縱坐標,主建物面積,附屬建物面積,平均單價元平方公尺,...,主要用途_集合住宅,主要建材_其他,主要建材_加強磚造,主要建材_鋼筋混凝土造,主要建材_鋼骨造,hospital_within_1km,mrt_numbs_within_1km,school_numbs_within_1km,store_numbs_within_0.5km,縣市區域價格
0,-0.541033,12,14,27.916667,-0.819326,179750,2499123,0.127159,-0.438452,103816.813612,...,0,0,0,1,0,1,4,10,6,4
1,0.753799,4,7,0.750000,0.311470,300436,2781335,-0.464083,-0.438452,103816.813612,...,0,0,0,1,0,1,2,17,12,10
2,0.482869,6,7,43.916667,-0.819326,302091,2773374,0.832407,-0.438452,82963.562500,...,0,0,0,1,0,0,4,32,18,10
3,0.390940,4,4,45.416667,-0.819326,298394,2775413,0.052476,-0.438452,137138.842105,...,0,0,1,0,0,1,2,6,24,9
4,-0.711599,3,8,27.250000,-0.819326,292572,2767887,-0.968196,-0.022099,201314.470149,...,0,0,0,1,0,0,0,12,11,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,-0.163249,25,25,1.500000,1.661628,184250,2502080,-0.496050,0.870392,55194.812500,...,1,0,0,1,0,1,1,6,3,4
5871,1.118749,6,17,17.583333,4.845468,308685,2771134,2.717029,-0.130991,133163.601485,...,0,1,0,0,0,0,3,8,21,10
5872,-0.053200,14,14,27.083333,-0.819326,287075,2773585,0.242296,-0.438452,103816.813612,...,0,0,0,1,0,0,1,4,14,9
5873,-0.089851,2,15,4.166667,-0.819326,185561,2504746,-0.257007,-0.438452,82639.428571,...,1,0,0,1,0,0,0,1,4,4
5874,1.475407,10,14,7.916667,1.748137,253067,2746655,1.500031,0.501012,69580.457831,...,0,0,0,1,0,0,0,4,10,8

In [11]:
private.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5875 entries, 0 to 5874
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   土地面積                      5875 non-null   float64
 1   移轉層次                      5875 non-null   int64
 2   總樓層數                      5875 non-null   int64
 3   屋齡                        5875 non-null   float64
 4   車位面積                      5875 non-null   float64
 5   橫坐標                       5875 non-null   int64
 6   縱坐標                       5875 non-null   int64
 7   主建物面積                     5875 non-null   float64
 8   附屬建物面積                    5875 non-null   float64
 9   平均單價元平方公尺                 5875 non-null   float64
 10  主要用途_商業用                  5875 non-null   int64
 11  主要用途_集合住宅                 5875 non-null   int64
 12  主要建材_其他                   5875 non-null   int64
 13  主要建材_加強磚造                 5875 non-null   int64
 14  主要建材_鋼筋混凝土造               5875 non-null   int64
 15  主要建材_鋼骨造                  5875 non-null   int64
 16  hospital_within_1km       5875 non-null   int64
 17  mrt_numbs_within_1km      5875 non-null   int64
 18  school_numbs_within_1km   5875 non-null   int64
 19  store_numbs_within_0.5km  5875 non-null   int64
 20  縣市區域價格                    5875 non-null   int64
dtypes: float64(6), int64(15)
memory usage: 964.0 KB

In [12]:
bus = pd.read_csv('bus_numbs_within_0.5km_pr.csv')
private.insert(21,'bus_numbs_within_0.5km', bus)

In [13]:
bike = pd.read_csv('bike_numbs_within_0.5km_pr.csv')
private.insert(22,'bike_numbs_within_0.5km', bike)

In [14]:
atm = pd.read_csv('atm_numbs_within_0.5km_pr.csv')
private.insert(23,'atm_numbs_within_0.5km', atm)

In [15]:
hos = pd.read_csv('hos_numbs_within_0.5km_pr.csv')
private.insert(24,'hos_numbs_within_0.5km', hos)

In [17]:
private

,土地面積,移轉層次,總樓層數,屋齡,車位面積,橫坐標,縱坐標,主建物面積,附屬建物面積,平均單價元平方公尺,...,主要建材_鋼骨造,hospital_within_1km,mrt_numbs_within_1km,school_numbs_within_1km,store_numbs_within_0.5km,縣市區域價格,bus_numbs_within_0.5km,bike_numbs_within_0.5km,atm_numbs_within_0.5km,hos_numbs_within_0.5km
0,-0.541033,12,14,27.916667,-0.819326,179750,2499123,0.127159,-0.438452,103816.813612,...,0,1,4,10,6,4,12,4,5,7
1,0.753799,4,7,0.750000,0.311470,300436,2781335,-0.464083,-0.438452,103816.813612,...,0,1,2,17,12,10,121,7,15,17
2,0.482869,6,7,43.916667,-0.819326,302091,2773374,0.832407,-0.438452,82963.562500,...,0,0,4,32,18,10,210,11,25,25
3,0.390940,4,4,45.416667,-0.819326,298394,2775413,0.052476,-0.438452,137138.842105,...,0,1,2,6,24,9,137,7,26,38
4,-0.711599,3,8,27.250000,-0.819326,292572,2767887,-0.968196,-0.022099,201314.470149,...,0,0,0,12,11,9,34,5,9,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,-0.163249,25,25,1.500000,1.661628,184250,2502080,-0.496050,0.870392,55194.812500,...,0,1,1,6,3,4,28,6,7,11
5871,1.118749,6,17,17.583333,4.845468,308685,2771134,2.717029,-0.130991,133163.601485,...,0,0,3,8,21,10,172,12,44,34
5872,-0.053200,14,14,27.083333,-0.819326,287075,2773585,0.242296,-0.438452,103816.813612,...,0,0,1,4,14,9,228,10,31,24
5873,-0.089851,2,15,4.166667,-0.819326,185561,2504746,-0.257007,-0.438452,82639.428571,...,0,0,0,1,4,4,14,2,4,2
5874,1.475407,10,14,7.916667,1.748137,253067,2746655,1.500031,0.501012,69580.457831,...,0,0,0,4,10,8,4,0,9,5

In [20]:
private.drop('hospital_within_1km', axis=1 ,inplace=True)

In [23]:
private.to_csv('dataset_1109_private.csv',index=False)